import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { CompiledContext, Rule, ScanResult, Token } from "../types.js";
import { deriveRules } from "./rules.js";

export const CONTEXT_DIR = ".tastefield";
const SCHEMA_VERSION = "0.1";

export function compile(scan: ScanResult): CompiledContext {
  return {
    version: SCHEMA_VERSION,
    generatedAt: new Date().toISOString(),
    repoRoot: scan.repoRoot,
    tokens: scan.tokens,
    components: scan.components,
    rules: deriveRules(scan),
    stack: scan.stack,
  };
}

function groupTokens(tokens: Token[]): Record<string, Token[]> {
  const groups: Record<string, Token[]> = {};
  for (const token of tokens) {
    (groups[token.kind] ??= []).push(token);
  }
  return groups;
}

/**
 * standards.md is the human-readable face of the compiled context. It's what a
 * design system manager reviews and what shows up in a PR diff — so it's written
 * as a document a person would sign off on, not as a prompt.
 */
function renderStandards(ctx: CompiledContext): string {
  const lines: string[] = [];

  lines.push("# Brand Standards");
  lines.push("");
  lines.push(
    "> Generated by Tastefield from this repository's design system. " +
      "These standards are served to AI coding agents over MCP and enforced by `tastefield check`."
  );
  lines.push("");

  const byCategory: Record<string, Rule[]> = {};
  for (const rule of ctx.rules) (byCategory[rule.category] ??= []).push(rule);

  const titles: Record<string, string> = {
    structure: "Component Contracts (Structural Standards)",
    boundary: "Brand Boundaries (Guardrails)",
    voice: "Voice & Copy Standards",
  };

  for (const category of ["structure", "boundary", "voice"] as const) {
    const rules = byCategory[category];
    if (!rules?.length) continue;

    lines.push(`## ${titles[category]}`);
    lines.push("");
    for (const rule of rules) {
      const enforced = rule.pattern ? "enforced" : "advisory";
      lines.push(`### \`${rule.id}\` — ${rule.severity} · ${enforced}`);
      lines.push("");
      lines.push(rule.statement);
      if (rule.fix) {
        lines.push("");
        lines.push(`**Instead:** ${rule.fix}`);
      }
      lines.push("");
    }
  }

  const groups = groupTokens(ctx.tokens);
  if (ctx.tokens.length) {
    lines.push("## Design Tokens");
    lines.push("");
    for (const [kind, tokens] of Object.entries(groups)) {
      lines.push(`**${kind}** (${tokens.length})`);
      lines.push("");
      lines.push("| Token | Value |");
      lines.push("| --- | --- |");
      for (const t of tokens) lines.push(`| \`--${t.name}\` | \`${t.value}\` |`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

/**
 * Write the compiled context to disk.
 *
 * Split across several files rather than one blob because the MCP server serves
 * them independently — an agent asking about copy tone shouldn't pull the entire
 * component contract set into its context window.
 */
export async function writeContext(
  repoRoot: string,
  ctx: CompiledContext
): Promise<string[]> {
  const dir = path.join(repoRoot, CONTEXT_DIR);
  await mkdir(dir, { recursive: true });

  const written: string[] = [];

  const files: Array<[string, string]> = [
    [
      "contracts.json",
      JSON.stringify(
        {
          version: ctx.version,
          generatedAt: ctx.generatedAt,
          stack: ctx.stack,
          components: ctx.components,
        },
        null,
        2
      ),
    ],
    [
      "tokens.json",
      JSON.stringify(
        {
          version: ctx.version,
          generatedAt: ctx.generatedAt,
          groups: groupTokens(ctx.tokens),
        },
        null,
        2
      ),
    ],
    [
      "rules.json",
      JSON.stringify(
        { version: ctx.version, generatedAt: ctx.generatedAt, rules: ctx.rules },
        null,
        2
      ),
    ],
    ["standards.md", renderStandards(ctx)],
    [
      "voice.json",
      JSON.stringify(
        {
          version: ctx.version,
          rules: ctx.rules.filter((r) => r.category === "voice"),
        },
        null,
        2
      ),
    ],
  ];

  for (const [name, content] of files) {
    const target = path.join(dir, name);
    await writeFile(target, content, "utf8");
    written.push(path.join(CONTEXT_DIR, name));
  }

  return written;
}
